### ISSUE TITLE
Dependent on feedparser

### ISSUE THREAD

**Issue by citelao** [T-Mac/Handle#1]
Requires python [feedparser](http://code.google.com/p/feedparser/downloads/detail?name=feedparser-5.0.1.zip&can=2&q=), which is not by default installed on many computers (including my Macbook)

Suggest updating README to show this, which I will fork to you.

**Comment by T-Mac** [comment]
README updated to show this dependency

**Comment by citelao** [comment]
Sorry about not forking anything over–– I had to leave and forgot about it.
