### ISSUE TITLE
Running Handle

### ISSUE THREAD

**Issue by dabaer** [T-Mac/Handle#4]
Could you please explain how to set this up, there is zero documentation on it. It would be helpful to address the following issues:
- Where to place the files (in the bukkit folder, in it's own folder
- Dependancies (Are these installed automatically)
- Explanation of the config (Port? Is this for minecraft or some sort of Handle remote access)
- Handle outputs nothing, and then appears to run in the background. The only thing I can get out of the log is if i run it twice, it complains that the port is in use.

**Comment by TokinT-Mac** [comment]
First off, having lost access to this github account, i've had to move here 
--> https://github.com/TokinT-Mac/Handle
If you are trying to install this to use you can download a zip here
--> https://www.dropbox.com/s/z6mwa8lrhl6dm45/Handle.zip
simply extract it and modify the "path_to_bukkit" value in handle.cfg to point to the directory containing craftbukkit.jar .
it is dependent on the plugin jsonapi --> http://mcjsonapi.com/
As far as the config values 'start_heap' and 'max_heap' are the same as java command line values
'port' is the local port handle uses to connect to its backend service
The JSON Api section are the values from the plugin.

I havent tested this in quite awhile so i have no idea if it works, it should but i dont have a linux box at the moment to test

**Comment by dabaer** [comment]
Does the jar need to be named craftbukkit.jar? We are using MCPC+.

**Comment by TokinT-Mac** [comment]
It does. Do keep in mind that this was originally written for bukkit, so it may or may not work.

**Comment by suresttexas00** [comment]
@TokinT-Mac you should update the page http://minecraft.gamepedia.com/Programs_and_editors/Server_wrappers
with your new repo.

**Comment by dabaer** [comment]
@suresttexas00 it's not exactly new, there haven't been updates in over 3 years :P Also i hadn't realized this is still open.

**Comment by suresttexas00** [comment]
I noted that, but It __is__ still listed on the server wrappers wiki.  Since it is in python, I thought I might have a look at it to learn with.
